// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rundan.Server.Data;

#nullable disable

namespace Rundan.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610085448_ScoreGameRounds")]
    partial class ScoreGameRounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Rundan.Server.Data.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestOfSets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourtLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamesToWinSet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideQuestionsFromHost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("MapCityCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Measurement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayersPerRound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadiusMeters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RandomizeQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreEntryMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoringMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("EventId", "Order");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("AwardedPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FreeText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("QuestionId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.BracketMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourtId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBye")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantAId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetScores")
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("ActivityId", "Side", "Round", "Slot");

                    b.ToTable("BracketMatches");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Order");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FixedTeamSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scoring")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlapMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamShuffle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.EventMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventMembers");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.EventViewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("EventViewers");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.MapCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Order");

                    b.ToTable("MapCities");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTeam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("ActivityId", "DisplayName")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.ParticipantMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ParticipantId", "UserId")
                        .IsUnique();

                    b.ToTable("ParticipantMembers");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptedArtist")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedFreeTextAnswer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadiusMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpotifyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Order");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptedFreeTextAnswer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuestionTemplates");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplateOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId");

                    b.ToTable("QuestionTemplateOptions");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplateTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId");

                    b.HasIndex("Tag");

                    b.ToTable("QuestionTemplateTags");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplateUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UsedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId")
                        .IsUnique();

                    b.ToTable("QuestionTemplateUsages");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("UserId");

                    b.HasIndex("ActivityId", "ParticipantId");

                    b.ToTable("ScoreEntries");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Slap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Penalty")
                        .HasColumnType("REAL");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlappedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlapperUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.ToTable("Slaps");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Activity", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Event", "Event")
                        .WithMany("Activities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Answer", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Participant", "Participant")
                        .WithMany("Answers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.AnswerOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Participant");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.AnswerOption", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.BracketMatch", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Activity");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Court", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Activity", "Activity")
                        .WithMany("Courts")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.EventMember", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Event", "Event")
                        .WithMany("Members")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.User", "User")
                        .WithMany("EventMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.EventViewer", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.MapCity", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Activity", "Activity")
                        .WithMany("MapCities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Participant", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Activity", "Activity")
                        .WithMany("Participants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.ParticipantMember", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Participant", "Participant")
                        .WithMany("Members")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Question", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Activity", "Activity")
                        .WithMany("Questions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplateOption", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.QuestionTemplate", "QuestionTemplate")
                        .WithMany("Options")
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionTemplate");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplateTag", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.QuestionTemplate", "QuestionTemplate")
                        .WithMany("Tags")
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionTemplate");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.ScoreEntry", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Activity", "Activity")
                        .WithMany("ScoreEntries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.Participant", "Participant")
                        .WithMany("ScoreEntries")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundan.Server.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("Participant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Slap", b =>
                {
                    b.HasOne("Rundan.Server.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Activity", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("MapCities");

                    b.Navigation("Participants");

                    b.Navigation("Questions");

                    b.Navigation("ScoreEntries");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Event", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Participant", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Members");

                    b.Navigation("ScoreEntries");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.QuestionTemplate", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Rundan.Server.Data.Entities.User", b =>
                {
                    b.Navigation("EventMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
